[workspace]
[package]
version = "0.1.0"
name = "check-adult-host"
edition = "2021"

[dependencies]
sp1-core = { git = "https://github.com/succinctlabs/sp1.git" }
serde = {version = "1.0", features = ["derive"]}
serde_json = "1.0"
chrono = "0.4"
